Updated the URL for W3C api docs
webrtc-for-the-curious/webrtc-for-the-curious pull request #245
Opened 2022-01-07 02:53 UTC by ahmed-adly-khalil

updated the W3C API link from https://w3c.github.io/webrtc-pc/ to https://www.w3.org/TR/webrtc/ as the latter is the official website and has more updates (Jan 26 vs Jan 6)

2022-01-07 14:28 UTC, mogren requested changes

2022-01-07 14:28 UTC, mogren commented on content/docs/01-what-why-and-how.md
> +The WebRTC protocol is maintained in the IETF in the [rtcweb](https://datatracker.ietf.org/wg/rtcweb/documents/) working group. The WebRTC API is documented in the W3C as [webrtc](https://w3c.github.
Thanks for catching this @ahmed-adly-khalil, but I think you forgot to actually change the link. https://www.w3.org/TR/webrtc/ does seem like the right URL.

2022-01-08 03:52 UTC, ahmed-adly-khalil commented on content/docs/01-what-why-and-how.md
> +The WebRTC protocol is maintained in the IETF in the [rtcweb](https://datatracker.ietf.org/wg/rtcweb/documents/) working group. The WebRTC API is documented in the W3C as [webrtc](https://w3c.github.
done, also updated the rest of languages

2022-01-08 04:12 UTC, mogren commented on content/docs/01-what-why-and-how.md
> +The WebRTC protocol is maintained in the IETF in the [rtcweb](https://datatracker.ietf.org/wg/rtcweb/documents/) working group. The WebRTC API is documented in the W3C as [webrtc](https://w3c.github.
Awesome, thanks!

2022-01-08 04:19 UTC, mogren approved these changes

2022-01-08 04:19 UTC, merged