fix index layout
webrtc-for-the-curious/webrtc-for-the-curious pull request #258
Opened 2022-02-24 06:07 UTC by katepangLiu

#257

2022-02-24 10:19 UTC, hiroyuki-sato requested changes
Hello, @katepangLiu.

Thank you for your great work. I checked your PR (Just the English part only). Could you check?

2022-02-24 10:19 UTC, hiroyuki-sato commented on content/docs/01-what-why-and-how.md
>  WebRTC, short for Web Real-Time Communication, is both an API and a Protocol. The WebRTC protocol is a set of rules for two WebRTC agents to negotiate bi-directional secure real-time communication. T
This part basically LGTM. I found `How does WebRTC (the API) work` parts contain four `#`.
What do you think to modify those parts?

```
grep -h '^#' content/docs/01-what-why-and-how.md
# What, Why and How
## What is WebRTC?
## Why should I learn WebRTC?
## The WebRTC Protocol is a collection of other technologies
### Signaling: How peers find each other in WebRTC
### Connecting and NAT Traversal with STUN/TURN
### Securing the transport layer with DTLS and SRTP
### Communicating with peers via RTP and SCTP
## WebRTC, a collection of protocols
## How does WebRTC (the API) work
#### `new RTCPeerConnection` # <-- HERE
#### `addTrack`
#### `createDataChannel`
#### `createOffer`
#### `setLocalDescription`
#### `setRemoteDescription`
#### `addIceCandidate`
#### `ontrack`
#### `oniceconnectionstatechange`
#### `onconnectionstatechange`
```

2022-02-24 10:19 UTC, hiroyuki-sato commented on content/docs/06-media-communication.md
> +
LGTM 👍

```
# Securing
## What security does WebRTC have?
## How does it work?
## Security 101
#### Plaintext and Ciphertext
#### Cipher
#### Hash functions
#### Public/Private Key Cryptography
#### Diffie–Hellman exchange
#### Pseudorandom Function
#### Key Derivation Function
#### Nonce
#### Message Authentication Code
#### Key Rotation
## DTLS
### Packet Format
#### Content Type
#### Version
#### Epoch
#### Sequence Number
#### Length and Payload
### Handshake State Machine
#### ClientHello
#### HelloVerifyRequest
#### ServerHello
#### Certificate
#### ServerKeyExchange/ClientKeyExchange
#### CertificateRequest
#### ServerHelloDone
#### CertificateVerify
#### ChangeCipherSpec
#### Finished
### Key Generation
### Exchanging ApplicationData
## SRTP
### Session Creation
### Exchanging Media
palolo:webrtc-for-the-curious hsato$
palolo:webrtc-for-the-curious hsato$ grep -h '^#' content/docs/06-securing.md
palolo:webrtc-for-the-curious hsato$ grep -h '^#' content/docs/06-media-communication.md
# Media Communication
## What do I get from WebRTC's media communication?
## How does it work?
## Latency vs Quality
### Real World Limitations
### Video is Complex
## Video 101
### Lossy and Lossless compression
### Intra and Inter frame compression
### Inter-frame types
### Video is delicate
## RTP
### Packet Format
#### Version (V)
#### Padding (P)
#### Extension (X)
#### CSRC count (CC)
#### Marker (M)
#### Payload Type (PT)
#### Sequence Number
#### Timestamp
#### Synchronization Source (SSRC)
#### Contributing Source (CSRC)
#### Payload
### Extensions
## RTCP
### Packet Format
#### Version (V)
#### Padding (P)
#### Reception Report Count (RC)
#### Packet Type (PT)
### Full INTRA-frame Request (FIR) and Picture Loss Indication (PLI)
### Negative Acknowledgment
### Sender and Receiver Reports
## How RTP/RTCP solve problems together
### Forward Error Correction
### Adaptive Bitrate and Bandwidth Estimation
## Identifying and Communicating Network Status
### Receiver Reports / Sender Reports
### TMMBR, TMMBN, REMB and TWCC, paired with GCC
#### Google Congestion Control (GCC)
#### TMMBR, TMMBN, and REMB
#### Transport Wide Congestion Control
## Bandwidth Estimation Alternatives
```

2022-02-24 10:19 UTC, hiroyuki-sato commented on content/docs/07-data-communication.md
> +
LGTM 👍

```
# Data Communication
## What do I get from WebRTC's data communication?
## How does it work?
## DCEP
### DATA_CHANNEL_OPEN
#### Packet Format
#### Message Type
#### Channel Type
#### Priority
#### Reliability Parameter
#### Label
#### Protocol
### DATA_CHANNEL_ACK
#### Packet Format
## Stream Control Transmission Protocol
## Concepts
### Association
### Streams
### Datagram Based
### Chunks
### Transmission Sequence Number
### Stream Identifier
### Payload Protocol Identifier
## Protocol
### DATA Chunk
### INIT Chunk
### SACK Chunk
### HEARTBEAT Chunk
### ABORT Chunk
### SHUTDOWN Chunk
### ERROR Chunk
### FORWARD TSN Chunk
## State Machine
### Connection Establishment Flow
### Connection Teardown Flow
### Keep-Alive Mechanism
```

2022-02-24 10:19 UTC, hiroyuki-sato commented on content/docs/09-debugging.md
>  Chrome comes with a built-in WebRTC statistics page available at [chrome://webrtc-internals](chrome://webrtc-internals).
This change looks good to me. What do you think to fix `Disable autofocus` and `Set focus to infinity` too?

```
grep -h '^#' content/docs/09-debugging.md
# Debugging
## Isolate The Problem
### Signaling Failure
### Networking Failure
### Security Failure
### Media Failure
### Data Failure
## Tools of the trade
### netcat (nc)
### tcpdump
### Wireshark
### webrtc-internals
## Latency
### Manual end-to-end latency measurement
### Automatic end-to-end latency measurement
#### Example latency estimation
#### Actual video time in browser
### Latency Debugging Tips
#### Camera latency
# Disable autofocus:
# Set focus to infinity:
#### Encoder latency
#### Network latency
#### Receiver side latency
```

2022-02-24 10:19 UTC, hiroyuki-sato commented on content/docs/02-signaling.md
>  When you create a WebRTC agent, it knows nothing about the other peer. It has no idea who it is going to connect with or what they are going to send!
This change looks good to me. I also found four `#` in `SDP Values used by WebRTC`.

```
# Signaling
## What is WebRTC Signaling?
## How does WebRTC signaling work?
## What is the *Session Description Protocol* (SDP)?
### How to read the SDP
### WebRTC only uses some SDP keys
### Media Descriptions in a Session Description
### Full Example
## How *Session Description Protocol* and WebRTC work together
### What are Offers and Answers?
### Transceivers are for sending and receiving
### SDP Values used by WebRTC
##### `group:BUNDLE`
##### `fingerprint:sha-256`
##### `setup:`
##### `ice-ufrag`
##### `ice-pwd`
##### `rtpmap`
##### `fmtp`
##### `candidate`
##### `ssrc`
### Example of a WebRTC Session Description
### Further Topics
```

2022-02-24 10:19 UTC, hiroyuki-sato commented on content/docs/04-securing.md
>  Every WebRTC connection is authenticated and encrypted. You can be confident that a 3rd party can't see what you are sending or insert bogus messages. You can also be sure that the WebRTC Agent that
This change also looks good to me. What do you think additional fix `Plaintext and Ciphertext` parts?

```
# Connecting
## Why does WebRTC need a dedicated subsystem for connecting?
### Reduced Bandwidth Costs
### Lower Latency
### Secure E2E Communication
## How does it work?
## Networking real-world constraints
### Not in the same network
### Protocol Restrictions
### Firewall/IDS Rules
## NAT Mapping
### Creating a mapping
### Mapping Creation Behaviors
#### Endpoint-Independent Mapping
#### Address Dependent Mapping
#### Address and Port Dependent Mapping
### Mapping Filtering Behaviors
#### Endpoint-Independent Filtering
#### Address Dependent Filtering
#### Address and Port Dependent Filtering
### Mapping Refresh
## STUN
### Protocol Structure
#### STUN Message Type
#### Message Length
#### Magic Cookie
#### Transaction ID
#### Data
### Create a NAT Mapping
### Determining NAT Type
## TURN
### TURN Lifecycle
#### Allocations
#### Permissions
#### SendIndication/ChannelData
#### Refreshing
### TURN Usage
#### One TURN Allocation for Communication
#### Two TURN Allocations for Communication
## ICE
### Creating an ICE Agent
### Candidate Gathering
#### Host
#### mDNS
#### Server Reflexive
#### Peer Reflexive
#### Relay
### Connectivity Checks
### Candidate Selection
### Restarts
```

2022-02-24 11:17 UTC, katepangLiu commented on content/docs/09-debugging.md
>  Chrome comes with a built-in WebRTC statistics page available at [chrome://webrtc-internals](chrome://webrtc-internals).
Haha, `# Disable autofocus`  `# Set focus to infinity` is in a code block. 
```
# Disable autofocus:
v4l2-ctl -d /dev/video0 -c focus_auto=0
# Set focus to infinity:
v4l2-ctl -d /dev/video0 -c focus_absolute=0
```

2022-02-24 11:19 UTC, katepangLiu commented on content/docs/01-what-why-and-how.md
>  WebRTC, short for Web Real-Time Communication, is both an API and a Protocol. The WebRTC protocol is a set of rules for two WebRTC agents to negotiate bi-directional secure real-time communication. T
Nice, I will fix it.

2022-02-24 11:20 UTC, katepangLiu commented on content/docs/02-signaling.md
>  When you create a WebRTC agent, it knows nothing about the other peer. It has no idea who it is going to connect with or what they are going to send!
Nice, I will fix it.

2022-02-24 11:23 UTC, katepangLiu commented on content/docs/04-securing.md
>  Every WebRTC connection is authenticated and encrypted. You can be confident that a 3rd party can't see what you are sending or insert bogus messages. You can also be sure that the WebRTC Agent that
Nice, I will fix it.

2022-02-24 11:35 UTC, katepangLiu commented
@hiroyuki-sato Can you double check for my new commit, thank you.

2022-02-24 12:27 UTC, hiroyuki-sato requested changes
Hello, @katepangLiu 

Thank you for your work. Could you double-check?

It seems that these contents need more work.

* content.sv/docs/05-real-time-networking.md
* content.zh-cn/docs/01-what-why-and-how.md
* content.zh-cn/docs/05-real-time-networking.md

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/02-signaling.md
> +# シグナリング
LGTM 👍

```
# シグナリング
## WebRTCシグナリングとは？
## WebRTC のシグナリングはどのように動作しますか？
## *Session Description Protocol* (SDP)とは？
### SDPの読み方
### WebRTCは一部のSDPキーしか使用しない
### Session Description に含まれるメディアの説明文
### Full Example
### 完全な例
## *SDP(Session Description Protocol)* と WebRTC の連携について
### オファーとアンサーとは？
### トランシーバーは送受信用
### WebRTC で使用される SDP の値
#### `group:BUNDLE`
#### `fingerprint:sha-256`
#### `setup:`
#### `ice-ufrag`
#### `ice-pwd`
#### `rtpmap`
#### `fmtp`
#### `candidate` (候補)
#### `ssrc`
### WebRTC Session Description の例
### その他のトピック
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/03-connecting.md
> +# 接続
LGTM 👍

```
# 接続
## なぜWebRTCには接続用の専用サブシステムが必要なのでしょうか？
### 帯域幅コストの削減
### 遅延の低減
### 安全なE2E通信
## どうやって使うの？
## ネットワークの現実的な制約
### 同じネットワークにいない
### プロトコルの制限
### ファイアウォール/IDSルール
## NATマッピング
### マッピングの作成
### マッピング作成時の動作
#### エンドポイントに依存しないマッピング
#### アドレスに依存するマッピング
#### アドレスとポートに依存するマッピング
### マッピングフィルタリングの動作
#### エンドポイントに依存しないフィルタリング
#### アドレスに依存したフィルタリング
#### アドレスとポートに依存したフィルタリング
### マッピングの更新
## STUN
### Protocol Structure
#### STUNメッセージのタイプ
#### メッセージの長さ (Message Length)
#### マジッククッキー (Magic Cookie)
#### トランザクションID (Transaction ID)
#### データ (Data)
### NAT マッピングの作成
### NAT の種類の決定
## TURN
### TURN ライフサイクル
#### アロケーション
#### パーミッション
#### SendIndication/ChannelData
#### Refreshing
### TURNの使い方
#### 通信のための1TURNの割り当て
#### コミュニケーションのための2つのTURNアロケーション
## ICE
### ICE エージェントの作成
### 候補者の収集
#### ホスト
#### mDNS
#### Server Reflexive
#### Peer Reflexive
#### リレー
### 接続性のチェック
### 候補者選定
### リスタート
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/04-securing.md
> +# セキュリティ対策
LGTM 👍
　

```
# セキュリティ対策
## WebRTCにはどんなセキュリティがありますか？
## どのような仕組みになっているのですか？
## セキュリティ101
### 暗号
### 平文/暗号文
### ハッシュ
### 公開鍵/秘密鍵暗号方式
### ディフィー・ヘルマン交換
### 擬似乱数関数
### 鍵導出関数
### ノンス
### メッセージ認証コード
### キー・ローテーション
## DTLS
### パケットフォーマット
#### コンテンツタイプ
#### バージョン
#### エポック
#### シーケンス番号
#### 長さとペイロード
### ハンドシェイクのステートマシン
#### ClientHello
#### HelloVerifyRequest
#### ServerHello
#### Certificate
#### ServerKeyExchange/ClientKeyExchange
#### CertificateRequest
#### ServerHelloDone
#### CertificateVerify
#### ChangeCipherSpec
#### Finished
### 鍵の生成
### アプリケーションデータの交換
## SRTP
### セッションの作成
### メディアの交換
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/05-real-time-networking.md
> +# リアルタイム・ネットワーキング
LGTM 👍

```
# リアルタイム・ネットワーキング
## リアルタイム・コミュニケーションにおいて、なぜネットワークが重要なのか？
## 難しくしているネットワークの属性は何ですか？
#### 帯域幅
#### 送信時間とラウンドトリップタイム
#### ジッター
#### パケットロス
#### 最大伝送単位
### 輻輳 (ふくそう)
### ダイナミック
## パケットロスの解決
### 確認応答 (Acknowledgments)
### 選択的確認応答 (Selective Acknowledgments)
### 否定確認応答 (Negative Acknowledgments)
### 前方誤り訂正 (Forward Error Correction)
## ジッターの解決
## 輻輳の検出
## 輻輳の解消
### 送信速度を遅くする
### より少ない情報を送る
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/06-media-communication.md
> +# メディア・コミュニケーション
LGTM 👍

```
# メディア・コミュニケーション
## WebRTCのメディア通信では何ができるのですか？
## どのような仕組みになっているのですか？
## レイテンシー vs クオリティ
### 現実の制約
### ビデオは複雑
## ビデオ101
### 非可逆圧縮と可逆圧縮
### イントラフレームとインターフレームの圧縮
### フレーム間の種類
### 動画はデリケート
## RTP
### パケットフォーマット
#### バージョン (V)
#### パディング (P)
#### 拡張 (X)
#### CSRC 数 (CC)
#### マーカー (M)
#### ペイロードタイプ (PT)
#### シーケンス番号
#### タイムスタンプ
#### 同期ソース (SSRC)
#### コントリビューションソース(CSRC)
#### ペイロード
### 拡張機能
## RTCP
### Packet Format
#### バージョン (V)
#### パディング (P)
#### 受信レポート数 (RC)
#### パケットタイプ (PT)
### Full INTRA-frame Request (FIR)とPicture Loss Indication (PLI)
### Negative ACKnowledgements
### 送信者/受信者レポート
## RTP/RTCPが共に問題を解決する方法
### Negative Acknowledgment
### 前方誤り訂正 (Forward Error Correction)
### 適応型ビットレートと帯域幅の推定 (Adaptive Bitrate and Bandwidth Estimation)
## ネットワーク状況の把握と伝達
### Receiver Reports / Sender Reports
### TMMBR、TMMBN、REMB、TWCC、GCCと対になる
#### Google輻輳制御（GCC)
#### TMMBR、TMMBN、および REMB
#### トランスポートワイド輻輳制御 (Transport Wide Congestion Control)
## 帯域幅の推定の代替案
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/07-data-communication.md
> +
LGTM 👍

```
# データ・コミュニケーション
## WebRTCのデータ通信で何が得られるのか？
## WebRTCはどのように動作するのですか？
## DCEP
### DATA_CHANNEL_OPEN
#### パケットフォーマット
#### メッセージタイプ
#### チャンネルタイプ
#### 優先順位
#### 信頼性パラメータ
#### ラベル
#### プロトコル
### DATA_CHANNEL_ACK
#### パケットフォーマット
## SCTP
## 概念
### アソシエーション
### ストリーム
### データグラムベース
### チャンク
## トランスミッションシーケンス番号
### ストリームの識別子
### ペイロードプロトコル識別子
## プロトコル
### DATA チャンク
### INIT チャンク
### SACK チャンク
### HEARTBEAT チャンク
### ABORT チャンク
### SHUTDOWN チャンク
### ERROR チャンク
### FORWARD TSN チャンク
## ステートマシン
### 接続確立の流れ
### コネクション・ティアダウンの流れ
### キープアライブの仕組み
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/09-debugging.md
> +## 問題の切り分け
LGTM 👍

```
# デバッグ
## 問題の切り分け
### シグナリングの失敗
### ネットワーキングの失敗
### セキュリティの失敗
### メディアの障害
### データの障害
## Tools of the trade
### netcat (nc)
### tcpdump
### Wireshark
### webrtc-internals
## レイテンシー
### 手動によるエンド・ツー・エンドのレイテンシー測定
### エンドツーエンドの遅延の自動測定
#### レイテンシー推定の例
#### ブラウザでの実際のビデオ時間
### レイテンシーのデバッグのヒント
#### カメラのレイテンシー
# オートフォーカスの無効化
# フォーカスを無限大にする
#### エンコーダーのレイテンシー
#### ネットワークのレイテンシー
#### 受信側のレイテンシー
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/01-what-why-and-how.md
> +# Vad, varför och hur
LGTM 👍

```
# Vad, varför och hur
## Vad är WebRTC?
## Varför ska jag lära mig WebRTC?
## WebRTC Protokollet är en samling av andra tekniker
### Signalering: Hur parter hittar varandra i WebRTC
### Anslutning och NAT Traversal med STUN/TURN
### Säkra transportskiktet med DTLS och SRTP
### Kommunicera med parter via RTP och SCTP
## WebRTC, en samling protokoll
## Hur fungerar API:et WebRTC
### `new RTCPeerConnection`
### `addTrack`
### `createDataChannel`
### `createOffer`
### `setLocalDescription`
### `setRemoteDescription`
### `addIceCandidate`
### `ontrack`
### `oniceconnectionstatechange`
### `onconnectionstatechange`
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/02-signaling.md
> +# Signalering
LGTM 👍

```
# Signalering
## Vad är WebRTC-signalering?
## Hur fungerar WebRTC-signalering?
## Vad är *Session Description Protocol* (SDP)?
### Hur man läser SDP
### WebRTC använder bara vissa SDP-nycklar
### Mediebeskrivningar i en sessionsbeskrivning
### Ett komplett exempel
## Hur *Session Description Protocol* och WebRTC fungerar tillsammans
### Vad är erbjudanden och svar?
### Transceivers är avsedda för sändning och mottagning
### SDP-värden som används av WebRTC
#### `grupp:BUNDLE`
#### `fingerprint:sha-256`
#### `setup:`
#### `ice-ufrag`
#### `ice-pwd`
#### `rtpmap`
#### `fmtp`
#### `candidate`
#### `ssrc`
### Exempel på en WebRTC-sessionsbeskrivning
### Ytterligare ämnen
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/03-connecting.md
> +# Anslutning
LGTM 👍

```
# Anslutning
## Varför behöver WebRTC ett särskilt delsystem för anslutning?
### Reducerade bandbreddskostnader
### Lägre latens
### Säker E2E-kommunikation
## Hur fungerar det?
## Nätverksbegränsningar
### Inte i samma nätverk
### Protokollbegränsningar
### Brandvägg/IDS-regler
## NAT-kartläggning
### Skapa en NAT-mappning
### Olika sorters NAT
#### Slutpunktoberoende mappning (Endpoint-Independent)
#### Adressberoende mappning
#### Adress- och port-beroende mappning
### Mappning av filtreringsbeteenden
#### Slutpunktsoberoende filtrering
#### Adressberoende filtrering
#### Adress- och port-beroende filtrering
### Uppdatera en mappning
## STUN
### Protokollstruktur
#### STUN Meddelande typ
#### Meddelandets längd
#### Magic Cookie
#### Transaktions ID
#### Data
### Skapa en NAT-mappning
### Bestämma NAT-typ
## TURN
### TURN Livscykel
#### Tilldelningar (Allocations)
#### Behörigheter
#### SendIndication/ChannelData
#### Refreshing
### TURN Användning
#### En TURN allokering för kommunikation
#### Två TURN allokeringar för kommunikation
## ICE
### Skapa en ICE-agent
### Kandidatsamling
#### Klient
#### mDNS
#### Serverreflexiv kandidat
#### Peer Reflexive
#### Relä (Relay)
### Anslutningskontroller
### Kandidatval
### Startar om
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/04-securing.md
> +# Säkerhet
LGTM 👍

```
# Säkerhet
## Säkerhet och WebRTC
## Hur fungerar det?
## Grundläggande säkerhet
### Klartext och Kryptotext
### Kryptering
### Hashfunktioner
### Kryptografi för offentlig / privat nyckel
### Diffie–Hellmans nyckelöverföring
### Pseudorandom-funktioner
### Key Derivation Function
### Nonce
### Meddelandeautentiseringskod
### Nyckelrotation
## DTLS
### Paketformat
#### Innehållstyp
#### Version
#### Epoch
#### Sekvensnummer
#### Längd och data
### Handskakningens tillstånd
#### ClientHello
#### HelloVerifyRequest
#### ServerHello
#### Certifikat
#### ServerKeyExchange/ClientKeyExchange
#### CertificateRequest
#### ServerHelloDone
#### CertificateVerify
#### ChangeCipherSpec
#### Färdiga
### Nyckelgenerering
### Utbyta applikationsdata
## SRTP
### Sessionsskapande
### Utbyta media
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/05-real-time-networking.md
> +# Realtidsnätverk
This part needs more work.

```
## Vilka egenskaper har nätverk som gör det svårt?
#### Bandbredd
```


```
# Realtidsnätverk
## Varför är nätverket så viktigt i realtidskommunikation?
## Vilka egenskaper har nätverk som gör det svårt?
#### Bandbredd
#### Sändningstid och rundturstid (Round Trip Time)
#### Jitter
#### Paketförlust
#### Maximal överföringsenhet
### Trängsel
### Dynamisk
## Lösa paketförlust
### Bekräftelser
### Selektiva bekräftelser
### Negativa bekräftelser
### Forward Error Correction
## Hantera jitter
### JitterBuffer-funktion
## Upptäcka trängsel
## Lösa trängsel
### Skicka långsammare
### Skicka mindre
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/06-media-communication.md
> +# Mediakommunikation
LGTM 👍

```
# Mediakommunikation
## Vad får jag från WebRTCs mediakommunikation?
## Hur fungerar det?
## Latens mot kvalitet
### Begränsningar i verkliga världen
### Video är komplext
## Video 101
### Förlustfri och inexakt komprimering
### Inexakt videokomprimering
### Dubbelriktad bildruta
### Video är känslig
## RTP
### Paketformat
#### Version (V)
#### Padding (P)
#### Tillägg (X)
#### CSRC-antal (CC)
#### Markör (M)
#### Payload Type (PT)
#### Sekvensnummer
#### Tidsstämpel
#### Synkroniseringskälla (SSRC)
#### Bidragande källa (CSRC)
#### Payload
### Tillägg
## RTCP
### Paketformat
#### Version (V)
#### Padding (P)
#### Antal mottagningsrapporter (RC)
#### Pakettyp (PT)
### Full INTRA-frame Request (FIR) och Picture Loss Indication (PLI)
### Negativa bekräftelser
### Avsändar- och mottagarrapporter
## Hur RTP/RTCP löser problem tillsammans
### Vidarekorrigering av fel
### Adaptiv bittakt och uppskattning av bandbredd
## Identifiera och kommunicera nätverksstatus
### Avsändar- och Mottagarrapporter
### TMMBR, TMMBN, REMB och TWCC, tillsammans med GCC
#### Google Congestion Control (GCC)
#### TMMBR, TMMBN, och REMB
### Transport Wide Congestion Control
## Alternativ för uppskattning av bandbredd
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/07-data-communication.md
> +# Datakommunikation
LGTM 👍

```
# Datakommunikation
## Vad får jag från WebRTCs datakommunikation?
## Hur fungerar det?
## DCEP
### DATA_CHANNEL_OPEN
#### Paketformat
#### Message Type
#### Channel Type
#### Prioritet
#### Pålitlighetsparameter
#### Etikett (Label)
#### Protokoll
### DATA_CHANNEL_ACK
#### Paketformat
## Stream Control Transmission Protocol
## Begrepp
### Association
### Strömmar
### Datagrambaserat
### Avsnitt
### Sändningssekvensnummer
### Strömidentifierare
### Payload Protocol Identifier
## Protokoll
### DATA-avsnitt
### INIT-avsnitt
### SACK-avsnitt
### HEARTBEAT-avsnitt
### ABORT-avsnitt
### SHUTDOWN-avsnitt
### ERROR-avsnitt
### FORWARD TSN-avsnitt
## Tillståndsmaskinen för SCTP
### Anslutningsetableringsflöde
### Anslutning av kopplingen
### Keep-Alive mekanism
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.sv/docs/09-debugging.md
> +# Felsökning
LGTM 👍

```
# Felsökning
## Isolera problemet
### Signalfel
### Nätverksfel
### Säkerhetsfel
### Mediefel
### Datafel
## Tools of the trade
### netcat (nc)
### tcpdump
### wireshark
### webrtc-internals
## Latens
### Manuell mätning från start till slut
### Automatisk start-till-slut-mätning
#### Exempel på latensuppskattning
#### Actual video time in browser
### Tips för att felsöka latensproblem
#### Kameralatens
#### Kodarens latens
#### Nätverksfördröjning
#### Latens på mottagarsidan
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/01-what-why-and-how.md
> +# WebRTC是什么，为什么，如何使用
LGTM 👍

```
# WebRTC是什么，为什么，如何使用
## WebRTC是什么？
## 为什么我应该学习WebRTC？
## WebRTC协议是一组其他技术的集合体
### 信令：peer如何在WebRTC中找到彼此
### 使用STUN/TURN进行连接和NAT穿透
### 使用DTLS和SRTP加密传输层
### 通过RTP和SCTP进行点对点通信
## WebRTC是一系列协议的集合
## WebRTC（API）如何工作
### `new RTCPeerConnection`
### `addTrack`
### `createDataChannel`
### `createOffer`
### `setLocalDescription`
### `setRemoteDescription`
### `addIceCandidate`
### `ontrack`
### `oniceconnectionstatechange`
### `onconnectionstatechange`
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/02-signaling.md
> +# 信令
LGTM 👍

```
# 信令
## 什么是WebRTC信令？
## WebRTC信令如何工作？
## 什么是 *会话描述协议*（SDP）？
### 如何阅读SDP信息
### WebRTC仅使用了部分SDP的key
### 会话描述中的媒体描述
### 完整示例
## *会话描述协议* 和WebRTC如何协同工作
### 什么是Offer和Answer？
### 用于发送和接收的收发器（Transceivers）
### WebRTC用到的SDP值
#### `group:BUNDLE`
#### `fingerprint:sha-256`
#### `setup:`
#### `ice-ufrag`
#### `ice-pwd`
#### `rtpmap`
#### `fmtp`
#### `candidate`
#### `ssrc`
### WebRTC会话描述示例
### 进一步的话题
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/03-connecting.md
> +# 连接
LGTM 👍

```
# 连接
## 为什么WebRTC需要专用的子系统进行连接？
### 降低带宽成本
### 更低延迟
### 安全的端到端通信
## 它是如何工作的？
## 现实世界的网络限制
### 不在同一个网络中
### 协议限制
### 防火墙/IDS规则
## NAT映射
### 创建映射
### 映射创建的行为
#### 端点无关的映射
#### 地址相关的映射
#### 地址和端口相关的映射
### 映射过滤行为
#### 端点无关的过滤
#### 地址相关的过滤
#### 地址和端口相关的过滤
### 映射的刷新
## STUN
### 协议结构
#### STUN 消息类型
#### 消息长度
#### Magic Cookie
#### 交互（Transaction）ID
#### 数据
### 创建NAT映射
### 确定NAT类型
## TURN
### TURN生命周期
#### Allocations
#### 权限
#### SendIndication/ChannelData
#### 刷新
### TURN 使用方法
#### 单个 TURN Allocation 通信
#### 双重 TURN Allocation 通信
## ICE
### 创建ICE Agent
### 候选地址收集
#### 主机
#### mDNS
#### 服务器自反（Server Reflextive）
#### Peer自反
#### 中继
### 连通性检查
### 候选地址选择
### 重新启动
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/04-securing.md
> +# 安全性
LGTM 👍

```
# 安全性
## WebRTC具有哪些安全性保障？
## 它是如何做到的？
## 安全性101
### 明文和密文
### Cipher
### 明文/密文
### 哈希函数
### 公钥/私钥加密
### Diffie-Hellman交换
### 伪随机函数（PRF）
### 密钥派生（KDF）
### Nonce
### 消息身份验证代码（Message Authentication Code）
### 密钥轮换
## DTLS
### 数据包格式
#### 内容类型
#### 版本
#### Epoch（时段）
#### 序列号
#### 长度和有效载荷
### `握手`状态机
#### ClientHello
#### HelloVerifyRequest
#### ServerHello
#### Certificate
#### ServerKeyExchange/ClientKeyExchange
#### CertificateRequest
#### ServerHelloDone
#### CertificateVerify
#### ChangeCipherSpec
#### Finished
### 密钥的生成
### 交换ApplicationData
## SRTP
### 会话创建
### 交换媒体数据
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/05-real-time-networking.md
> +## 实时网络
`## 实时网络` -> `# 实时网络`

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/06-media-communication.md
> +# 媒体通信
LGTM 👍

```
# 媒体通信
## 我可以从WebRTC的媒体通信中得到什么？
## 它是如何工作的？
## 延迟与质量
### 现实世界的局限性
### 视频是复杂的
## 视频101
### 有损和无损压缩
### 帧内和帧间压缩
### 帧间压缩
### 视频很脆弱
## RTP
### Packet Format（包格式）
#### Version (V)
#### Padding (P)
#### Extension (X)
#### CSRC count (CC)
#### Marker (M)
#### Payload Type (PT)
#### Sequence Number
#### Timestamp
#### Synchronization Source (SSRC)
#### Contributing Source (CSRC)
#### Payload
### Extensions（扩展）
## RTCP
### Packet Format
#### Version (V)
#### Padding (P)
#### Reception Report Count (RC)
#### Packet Type (PT)
### 完整的帧内请求（FIR）和图片丢失指示（PLI）
### Negative ACKnowledgements（否定确认）
### Sender and Receiver Reports（发送方和接收方报告）
## RTP/RTCP是如何协作解决问题的
### Forward Error Correction（前向纠错）
### 自适应比特率和带宽估计
## 识别和传递网络状态
###  Receiver Reports / Sender Reports
### TMMBR，TMMBN，REMB 和 TWCC, 与GCC配合
#### Google Congestion Control (GCC)
#### TMMBR, TMMBN, and REMB
### 传输范围内的拥塞控制（TWCC）
## 生成带宽估计值
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/07-data-communication.md
> +# 数据通信
LGTM 👍

```
# 数据通信
## 我可以从WebRTC的数据通信中获得什么？
## 它是如何工作的？
## DCEP
### DATA_CHANNEL_OPEN
#### 封包格式
#### 消息类型（Message Type）
#### 通道类型（Channel Type）
#### 优先级（Priority）
#### 可靠性参数
#### 标签（Label）
#### 协议（Protocol）
### DATA_CHANNEL_ACK
#### 封包格式
## 流控传输协议（SCTP）
## 概念
### 关联（Association）
### 流
### 基于数据报
### 块（Chunks）
### 传输序列号
### 流标识符
### 有效负载协议标识符
## 协议
### DATA块
### INIT块
### SACK块
### HEARTBEAT块
### ABORT块
### SHUTDOWN块
### ERROR块
### FORWARD TSN块
## 状态机
### 连接建立流程
### 连接关闭流程
### Keep-Alive（保持活动）机制
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.zh-cn/docs/09-debugging.md
> +
LGTM 👍

```
# 调试
## 分解问题
### 信令故障
### 网络故障
### 安全故障
### 媒体故障
### 数据故障
## 用到的工具
### netcat (nc)
### tcpdump
### wireshark
### webrtc-internals
## 延迟(Latency)
### 端到端延迟——手动测量
### 端到端延迟——自动测量
#### 延迟测量示例
#### 浏览器中的视频准确时间
### 延迟的调试技巧
#### 相机延迟
#### 编码延迟
#### 网络延迟
#### 接收方一侧的延迟
```

2022-02-24 12:27 UTC, hiroyuki-sato commented on content.ja/docs/01-what-why-and-how.md
> +# 何を、なぜ、どのように
LGTM 👍

```
# 何を、なぜ、どのように
## WebRTCとは？
## なぜWebRTCを学ぶ必要があるのか？
## WebRTCプロトコルは他の技術の集合体である
### シグナリング: WebRTCでピアがお互いを見つける方法
### STUN/TURN による接続と NAT トラバーサル
### DTLS と SRTP によるトランスポート層のセキュリティ確保
### RTP および SCTP によるピアとの通信
## プロトコルの集合体であるWebRTC
## WebRTC (API) はどのように動作するか
### `new RTCPeerConnection`
### `addTrack`
### `createDataChannel`
### `createOffer`
### `setLocalDescription`
### `setRemoteDescription`
### `addIceCandidate`
### `ontrack`
### `oniceconnectionstatechange`
### `onconnectionstatechange`
```

2022-02-24 13:39 UTC, katepangLiu commented
> Hello, @katepangLiu
> 
> Thank you for your work. Could you double-check?
> 
> It seems that these contents need more work.
> 
> * content.sv/docs/05-real-time-networking.md
> * content.zh-cn/docs/01-what-why-and-how.md
> * content.zh-cn/docs/05-real-time-networking.md

Thank you very much, @hiroyuki-sato ，checking headers with `grep` is so helpful.     

```
$ grep '#' content.sv/docs/05-real-time-networking.md
# Realtidsnätverk
## Varför är nätverket så viktigt i realtidskommunikation?
## Vilka egenskaper har nätverk som gör det svårt?
### Bandbredd
### Sändningstid och rundturstid (Round Trip Time)
Tekniken WebRTC använder för att mäta rundturstid beskrivs mer detaljerat i [kapitlet om RTCP Sender and Receiver Reports](../06-media-communication/#senderreceiver-reports).
### Jitter
### Paketförlust
### Maximal överföringsenhet
### Trängsel
### Dynamisk
## Lösa paketförlust
### Bekräftelser
### Selektiva bekräftelser
### Negativa bekräftelser
### Forward Error Correction
## Hantera jitter
### JitterBuffer-funktion
Läs mer om hur video konverteras till RTP-paket och varför rekonstruktion är nödvändig [i kapitlet om mediekommunikation](../06-media-communication/#rtp).
Det är en del av [WebRTC Statistics API](https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay) och spelar roll för mottagarens inkommande videoström.
## Upptäcka trängsel
## Lösa trängsel
### Skicka långsammare
### Skicka mindre
```

```
$ grep '#' content.zh-cn/docs/01-what-why-and-how.md
# 是什么，为什么，如何使用
## WebRTC是什么？
## 为什么我应该学习WebRTC？
## WebRTC协议是一组其他技术的集合体
### 信令：peer如何在WebRTC中找到彼此
### 使用STUN/TURN进行连接和NAT穿透
### 使用DTLS和SRTP加密传输层
### 通过RTP和SCTP进行点对点通信
## WebRTC是一系列协议的集合
## WebRTC（API）如何工作
### `new RTCPeerConnection`
### `addTrack`
### `createDataChannel`
### `createOffer`
### `setLocalDescription`
### `setRemoteDescription`
### `addIceCandidate`
### `ontrack`
### `oniceconnectionstatechange`
### `onconnectionstatechange`
```

```
$ grep '#' content.zh-cn/docs/05-real-time-networking.md
# 实时网络
## 为什么网络在实时通信中如此重要？
## 使网络变得困难的有哪些属性？
### 带宽
### 传输时间和往返时间
关于往返时间测量的技术，在[RTCP的发送方和接收方报告章节](../06-media-communication/#senderreceiver-reports发送方接收方报告)中有更详细的描述。
### 抖动
### 数据包丢失
### 最大传输单位（MTU）
### 拥塞
### 动态变化
## 解决数据包丢失问题
### 确认（Acknowledgments）
### 选择性确认（Selective Acknowledgments）
### 否定应答（Negative Acknowledgments）
### 前向纠错（FEC）
## 解决抖动问题
### JitterBuffer（抖动缓冲区）操作
关于视频帧是如何转换为RTP数据包，以及为何需要重建视频帧的知识，你可以[在媒体通信章节中](../06-media-communication/#rtp)读到更多。
它是[WebRTC统计API](https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay)中的一部分，与接收方的入站流有关。
## 检测拥塞问题
## 解决拥塞问题
### 降低发送速度
### 减少发送的数据
```

2022-02-24 13:45 UTC, hiroyuki-sato approved these changes
Hello, @katepangLiu 
Thanks! LGTM 👍. Please wait for @mogren and @voluntas review.

2022-02-24 14:40 UTC, mogren commented
Awesome, thanks for fixing this. LGTM!

2022-02-25 02:11 UTC, katepangLiu commented on content.sv/docs/09-debugging.md
> +## Tools of the trade
With pleasure.

2022-02-25 06:41 UTC, hiroyuki-sato commented
@mogren Could you check the final change `Praktiska verktyg`. If it's OK, could you merge this PR?
@katepangLiu Thanks!!

2022-02-25 21:05 UTC, merged