update Hash functions
webrtc-for-the-curious/webrtc-for-the-curious pull request #265
Opened 2022-03-09 02:06 UTC by Dw9

2022-03-09 12:30 UTC, katepangLiu requested changes
Thanks @Dw9 .
感觉还不是很流程，哈哈
提个小建议，一起探讨一下：
哈希函数可以很简单，比如只是对输入间隔取字母，简单地把`HELLO`变成`HLO` 。

2022-03-09 13:52 UTC, Dw9 commented
感谢建议。确实一字一词翻的有点生硬。您这样会更好理解一点！对照原文，如下版本您觉得怎样

> 哈希函数可以很简单，比如只是对输入间隔取字母。这样HELLO将变成HLO。

2022-03-09 14:03 UTC, katepangLiu commented
> 感谢建议。确实一字一词翻的有点生硬。您这样会更好理解一点！对照原文，如下版本您觉得怎样
> 
> > 哈希函数可以很简单，比如只是对输入间隔取字母。这样HELLO将变成HLO。

Nice.

2022-03-10 02:19 UTC, hiroyuki-sato commented
@Dw9 Thank you for your PR!
@katepangLiu Does this PR merge ready? (I merge if you LGTM comment :smile: ).

2022-03-10 03:00 UTC, katepangLiu approved these changes

2022-03-10 03:03 UTC, merged

2022-03-10 03:03 UTC, hiroyuki-sato commented
Thanks!