First chapter translated to French
webrtc-for-the-curious/webrtc-for-the-curious pull request #282
Opened 2022-06-09 11:59 UTC by daimoc

I start a French translation.

2022-06-09 17:53 UTC, mogren requested changes
Awesome, thank you! 

Just one thing, the "images" folder in content.fr should just be a soft link to the "docs/images/" one, no need to make duplicates. Also, there seem to be some broken pngs in there as well.

2022-06-09 21:15 UTC, daimoc commented
Thank you for the review @mogren, I didn't see that the symlink was replaced by a real copy. 
I fixed it.

2022-06-09 21:19 UTC, mogren approved these changes

2022-06-09 21:26 UTC, mogren commented
It looks good to me, but I'll give others a chance to comment before I submit it. Thanks again for the work, and if you find something in the english text that doesn't seem right, feel free to address it or open an issue about it. 😄

2022-06-10 01:00 UTC, hiroyuki-sato commented on content.fr/_index.md
> +Ce livre a été créé par des experts  WebRCT afin de partager leurs savoir durement acquis avec le monde.
WebRCT -> WebRTC (I can't read French by the way)
Thank you for your translation work!

2022-06-10 09:18 UTC, daimoc commented on content.fr/_index.md
> +Ce livre a été créé par des experts  WebRCT afin de partager leurs savoir durement acquis avec le monde.
Thanks for catching this. It's fixed.

2022-06-10 09:20 UTC, hiroyuki-sato approved these changes

2022-06-10 16:30 UTC, merged

2022-06-10 16:33 UTC, mogren commented
C'est magnifique!  https://webrtcforthecurious.com/fr/