Add Indonesian (ID) translation
webrtc-for-the-curious/webrtc-for-the-curious pull request #287
Opened 2022-06-28 09:22 UTC by fitraditya

Add Indonesian (ID) translation. First chapter translated, more chapter later.

2022-06-28 13:38 UTC, hiroyuki-sato commented
Hello, @fitraditya. Thank you for your contribution. I read your PR(`_index.md` and `01-what-why-and-how`) using Google Translate. It seems good.

@mogren Please take a look when you get a chance.

2022-06-28 13:38 UTC, hiroyuki-sato approved these changes

2022-06-28 13:43 UTC, hiroyuki-sato requested changes

2022-06-28 13:43 UTC, hiroyuki-sato commented on config.toml
> +  [languages.fr]
`languages.id` ?

2022-06-28 20:21 UTC, mogren approved these changes
Nice @fitraditya, thanks for working on this! 🎉

2022-06-29 00:09 UTC, hiroyuki-sato approved these changes
@fitraditya Thanks!
@mogren Thank you for your review.

2022-06-29 00:09 UTC, merged